### PR TITLE
Serialized Beat Object

### PR DESCRIPTION
**Pull request by JousterL**
Wanted to speed up the ability to play around with files without waiting the whole processing time each run. If you specify the -b argument it'll write out a .beat file serialized with Pickle so that that computation doesn't need to be re-run.

### CODE REVIEW

**Comment by dhsavell** [comment]
Thanks for the contribution! This is a great addition for CLI users. I'll switch this over to the develop branch (which should work either out-of-the-box or with minor changes) and hopefully merge everything soon for a release before the end of the month.

**Comment by dhsavell** [comment]
Some stuff got shuffled up around the argument parser and creating the Beats object but it doesn't look like anything too crazy. If you get the chance to fix the conflict then feel free to do it at your leisure, otherwise no sweat since I can take care of it for release.

**Comment by JousterL** [comment]
Might have to ask for your help on the integration with the new code. In 2.4 the Beat object returned as a list: Beats(list(loader(path_or_fp)))
But in 3.0 devel it's returned as a Generator: Beats(sr, channels, beats) which can't be Pickled.

I'm afraid of damaging the construct/throwing away too much data if I try to convert it, as I'm unfamiliar with the exact structure of the object (I was just sort of treating it as a black box that I could throw at Pickle).

**Comment by dhsavell** [comment]
Not a problem! I'll see what I can do for a workaround and then get this merged in.

**Comment by dhsavell** [comment]
It looks like I made an oversight while updating that class. The `_beats` field was supposed to be a list like the type annotation said, not a generator. I just committed an update to the base branch so I think your approach will work now. Thanks for your cooperation.

**Comment by JousterL** [comment]
Yeah, that fixed it. I had to bypass your use of soundfile in the beats.py, as it was trying to seek on the _io.BufferedWriter of p.stdin, which threw an Illegal Seek. I'll throw a separate PR to you for that one.

**Comment by dhsavell** [comment]
Thanks a ton for dealing with the unpolished dev code. This should be live in a full release pretty soon.

**Pull request merged**
